feat: Add keepalived to Anvil, extend bootstrap to include --vip option
canonical/maas-anvil pull request #17
Opened 2024-06-13 14:45 UTC by SK1Y101

Add the keepalived charm to MAAS-anvil.
Allow specifying the virtual IP at cluster bootstrap

2024-06-27 10:23 UTC, skatsaounis commented on anvil-python/anvil/jobs/common.py
> +def validate_ip_address(
Maybe we need to remove that too

2024-06-27 10:23 UTC, skatsaounis commented on anvil-python/anvil/provider/local/commands.py
> +    validate_ip_address,
same here for all the changes in `commands.py`

2024-06-27 10:23 UTC, skatsaounis commented on cloud/etc/deploy-haproxy/main.tf
> +}
nit: what about a new line in the end of the file?

2024-06-27 10:23 UTC, skatsaounis commented on cloud/etc/deploy-haproxy/variables.tf
> +}
nit: what about a new line in the end of the file?

2024-06-27 10:23 UTC, skatsaounis commented on anvil-python/anvil/commands/haproxy.py
> +                "virtual_ip": PromptQuestion(
what about adding the `validation_function` here? https://github.com/canonical/snap-openstack/blob/anvil-0.1/sunbeam-python/sunbeam/jobs/questions.py#L105

2024-06-27 10:24 UTC, skatsaounis commented on anvil-python/anvil/jobs/common.py
> +def validate_ip_address(
Or repurpose it to be a question validation function as suggested below

2024-07-01 09:10 UTC, skatsaounis requested changes
Great job @SK1Y101. I think that we need to update the README.md part that is referencing the VIP addition. After that, we are good to merge :tada:

2024-07-01 10:31 UTC, skatsaounis requested changes

2024-07-01 10:31 UTC, skatsaounis commented on README.md
> +During installation of the HAProxy charm, you will be asked for a virtual_ip. Pass an empty value to disable it.
If `accept_defaults` is used, do we still receive the question?

2024-07-01 10:31 UTC, skatsaounis commented on README.md
> +During installation of the HAProxy charm, you will be asked for a virtual_ip. Pass an empty value to disable it.
```suggestion

During installation of the HAProxy charm, you will be asked for a `virtual_ip`. Pass an empty value to disable it.
```

2024-07-01 10:31 UTC, skatsaounis commented on README.md
> +Passing any other valid IP will install the KeepAliveD charm, allowing you to connect to HA MAAS using the VIP.
```suggestion
Passing any other valid IP will install the Keepalived charm, allowing you to connect to HA MAAS using the VIP.
```

2024-07-01 10:31 UTC, skatsaounis commented on README.md
> +During installation of the HAProxy charm, you will be asked for a virtual_ip. Pass an empty value to disable it.
```suggestion

During installation of the HAProxy charm, you will be asked for a `virtual_ip`. Pass an empty value to disable it.
```

2024-07-01 10:31 UTC, skatsaounis commented on README.md
> +Passing any other valid IP will install the KeepAliveD charm, allowing you to connect to HA MAAS using the VIP.
```suggestion
Passing any other valid IP will install the Keepalived charm, allowing you to connect to HA MAAS using the VIP.
```

2024-07-01 10:31 UTC, skatsaounis commented on README.md
> +During installation of the HAProxy charm, you will be asked for a virtual_ip. Pass an empty value to disable it.
Maybe we need to investigate a bit to make this question not been asked on joining new nodes.

2024-07-01 15:08 UTC, SK1Y101 commented on anvil-python/anvil/commands/haproxy.py
> +        previous_answers = load_answers(self.client, CONFIG_KEY)
In theory this should fix #27

2024-07-05 14:47 UTC, SK1Y101 commented
@skatsaounis do these changes work for you?

2024-07-08 12:09 UTC, skatsaounis approved these changes
LGTM with today's changes. It is also passing my local tests successfully. I can set the VIP through the CLI prompt or a manifest. Or I can proceed without specifying a VIP. When I join another haproxy node I also have the option to accept-defaults or remember the previous answer.

@SK1Y101 could you also please take a look at the changes and then merge or update any needed change? Thank you :slightly_smiling_face:

2024-07-08 12:16 UTC, SK1Y101 commented
@skatsaounis the changes look good to me, if it passes the functional tests and you can see the expected behavior in testing I'm happy!

2024-07-08 13:59 UTC, merged