feat: add juju-login command
canonical/maas-anvil pull request #34
Opened 2024-07-08 15:04 UTC by SK1Y101

- should address #12 
- allow running `maas-anvil juju-login` to re-auth the terminal session

2024-07-10 20:34 UTC, wyattrees approved these changes
Looks good!

2024-07-11 07:02 UTC, skatsaounis requested changes

2024-07-11 09:03 UTC, skatsaounis submitted a review, later dismissed
LGTM +1

2024-07-11 09:25 UTC, skatsaounis approved these changes
LGTM +1

2024-07-11 09:45 UTC, merged