feat: Add node's ssh key to Juju model on join
canonical/maas-anvil pull request #38
Opened 2024-07-16 23:23 UTC by wyattrees

Uses `juju add-ssh-key` to add the node's public key to the model, allowing users to ssh to each machine with `juju ssh`

2024-07-17 10:22 UTC, skatsaounis requested changes
Overall the changes look pretty good. I added some comments which can easily be resolved and after that we can merge the PR :slightly_smiling_face:

2024-07-17 10:22 UTC, skatsaounis commented on anvil-python/anvil/utils.py
Are the changes in this file really needed or are they leftovers from development?

2024-07-17 10:22 UTC, skatsaounis commented on anvil-python/anvil/commands/juju.py
> +class JujuAddSshKeyStep(BaseStep):
Nit:

```suggestion
class JujuAddSSHKeyStep(BaseStep):
```

If you agree with the change you also need to change it to `provider/local/commands.py`; import+usage

2024-07-17 10:22 UTC, skatsaounis commented on anvil-python/anvil/provider/local/commands.py
> +    plan2.append(JujuAddSshKeyStep())
IMHO this has to be the last step of `plan1` because this is the place where you are adding the machine to juju model.

2024-07-17 14:53 UTC, wyattrees commented on anvil-python/anvil/utils.py
not needed. I (incorrectly) assumed our formatter would remove these imports

2024-07-18 10:36 UTC, skatsaounis approved these changes
LGTM +1

2024-07-18 11:17 UTC, skatsaounis commented
@wyattrees could you please sign the commits in order to merge this? Feel free to also squash into 1 with only you as a committer. :slightly_smiling_face:

2024-07-18 14:58 UTC, merged